# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Provider')),
                ('plan_name', models.CharField(max_length=50, verbose_name='PlanName')),
                ('plan_id', models.CharField(max_length=50, verbose_name='PlanID')),
                ('plan_type', models.CharField(choices=[('d', 'Discount'), ('f', 'Fixed'), ('p', 'Peak')], max_length=1, verbose_name='PlanType')),
                ('discount', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='DiscountRate')),
                ('fixed_rate', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='FixedRate')),
                ('peak_rate', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='PeakRate')),
                ('offpeak_rate', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='OffpeakRate')),
                ('peak_start', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='PeakStart')),
                ('peak_end', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='PeakEnd')),
                ('monthly_fixed_cost', models.DecimalField(decimal_places=9, max_digits=15, verbose_name='MonthlyFixedCost')),
                ('one_time_fixed_cost', models.DecimalField(decimal_places=9, max_digits=15, verbose_name='One-TimeFixedCost')),
                ('contract_period', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='ContractPeriod')),
                ('smart_meter', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, verbose_name='SmartMeter')),
                ('remarks', models.CharField(max_length=200, verbose_name='Remarks')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
            ],
        ),
    ]
