# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='other_cost_eqn',
            field=models.CharField(default=0, max_length=200, verbose_name='OtherCostEqn'),
            preserve_default=False,
        ),
    ]
