# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0003_priceplan_tlf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceplan',
            old_name='offpeak_rate',
            new_name='offpeak_rate_wd',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='peak_end',
            new_name='peak_end_wd',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='peak_rate',
            new_name='peak_rate_wd',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='peak_start',
            new_name='peak_start_wd',
        ),
        migrations.AddField(
            model_name='priceplan',
            name='ami_fee',
            field=models.CharField(default=0, max_length=200, verbose_name='AMIInstallationFee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='early_termination_charge',
            field=models.CharField(default=0, max_length=200, verbose_name='EarlyTerminationCharge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='late_payment_charge',
            field=models.CharField(default=0, max_length=200, verbose_name='LatePaymentCharge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='offpeak_rate_we',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='OffpeakRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='peak_end_we',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='PeakEnd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='peak_rate_we',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10, verbose_name='PeakRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='peak_start_we',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='PeakStart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='smart_meter',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('o', 'Optional')], max_length=1, verbose_name='SmartMeter'),
        ),
    ]
