# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0005_auto_20180508_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='factsheet_date',
            field=models.CharField(default='0', max_length=200, verbose_name='FactsheetDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priceplan',
            name='security_deposit',
            field=models.CharField(default='0', max_length=200, verbose_name='SecurityDeposit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.CharField(choices=[('d', 'Discount'), ('f', 'Fixed'), ('p', 'Peak'), ('fl', 'Flat'), ('pd', 'PeakDiscount')], max_length=1, verbose_name='PlanType'),
        ),
    ]
