# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0006_auto_20180509_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Provider')),
                ('plan_name', models.CharField(max_length=50, verbose_name='PlanName')),
                ('plan_id', models.CharField(max_length=50, verbose_name='PlanID')),
                ('plan_type', models.CharField(choices=[('d', 'Discount'), ('f', 'Fixed'), ('p', 'Peak'), ('fl', 'Flat'), ('pd', 'PeakDiscount')], max_length=1, verbose_name='PlanType')),
                ('discount', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='DiscountRate')),
                ('fixed_rate', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='FixedRate')),
                ('peak_rate_wd', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='PeakRate')),
                ('other_cost_eqn', models.CharField(max_length=200, verbose_name='OtherCostEqn')),
                ('lf', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='TLF')),
            ],
        ),
    ]
