# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0007_simplepriceplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplepriceplan',
            old_name='lf',
            new_name='tlf',
        ),
    ]
