# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0008_auto_20180510_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepriceplan',
            name='tlf',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='TLF'),
        ),
    ]
