# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0009_auto_20180510_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='clean_energy',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='CleanEnergy'),
            preserve_default=False,
        ),
    ]
