# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_electricity', '0010_priceplan_clean_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='plan_type',
            field=models.CharField(choices=[('d', 'Discount'), ('f', 'Fixed'), ('p', 'Peak'), ('fl', 'Flat'), ('pd', 'PeakDiscount')], max_length=2, verbose_name='PlanType'),
        ),
    ]
